### PR TITLE
Array types support

### PR DESCRIPTION
**Pull request by frostiq**

### CODE REVIEW

**Comment by buybackoff** [comment]
Thanks, especially for the tests! I assume they pass, haven't added Travis to this repo yet. Recursive lambdas and regex are cool, but we do the check of a type being an array twice. Performance is of the last concern here, but the logic could probably be simple. E.g. we could find the position of `[` and if it is present be sure that the type is an array and store a local `boolean`. Then we could take a substring before the index of `[` and parse it normally as if it was not an array type, and as the last step map the output types `.map(x => x+'[]')` if the type is an array as we have determined on the first step.

Some pseudocode:

```
1. let isArray =  position of `[` is > 0
2. let typeToParse = isArray ? substring before `[` : original
3. let outputTypes: string[] = parse(typeToParse)
4. let result = (isArray ? outputTypes.map(x => x+'[]') : outputTypes).join(' | ')
```

Anyway, I will merge as is tomorrow afternoon and publish a patch to npm if you won't change the current code.

**Comment by frostiq** [comment]
Thank you for a quick response!
I think you are right and it is not a big change, so I will update my pull request today

**Comment by frostiq** [comment]
And about tests:
Some tests are failing even before my change..
Maybe I've started it in a wrong way..
My steps were:
```
npm i
truffle compile
npm test
```

**Comment by buybackoff** [comment]
Cool! Thanks
One test used to randomly fail with time travel in TestRPC, need to fix a condition to account for milliseconds rounding. Will check other tests and add Travis later.

**Comment by frostiq** [comment]
Do you have any plans for updating npm package?

**Comment by buybackoff** [comment]
updated to 0.9.11

**Comment by frostiq** [comment]
Thanks!

**Pull request merged**
